### PR TITLE
typechecker: document 3rd party limitation

### PR DESCRIPTION
**Pull request by ahmed-mez**
### What does this PR do?

Document that the type checker doesn't work with 3rd party imports currently

### Reviewer's Checklist

- [ ] Changed code has unit tests for its functionality.

### CODE REVIEW

**Comment by darccio** [comment]
@ahmed-mez Isn't this PR reviewed and merged for some reason previous to me joining the company?

**Comment by ahmed-mez** [comment]
@darccio there was a discussion about whether we really need a type checker for 3rd party libraries, currently the answer is no but we might have use-cases in the future where we'll need the type checker. This PR is just for documentation purpose, we can either merge it or just open an issue (it's tracked on Jira already).

**Comment by darccio** [comment]
@ahmed-mez I would merge it. Maybe somebody else will be inspired by the comment and try to find an alternative.

**Comment by ahmed-mez** [comment]
Alright then, could you review?

**Review by darccio — APPROVED** [review]

**Pull request merged**
